const mealArr = [
    {   id: 1,
        title: 'Korean BBQ Short Ribs (Galbi)',
        img: '/images/KBBQ.jpeg',
        description: 'Marinated short ribs accompanied with Jasmine Rice, Mixed Greens and Kimchi.',
        calories: '710 cal/serv',
        rating: 4.5,
        numReviews: 40,
    },
    {   id: 2,
        title: 'Seaseme Garlic Chicken Lo Mein',
        img: '/images/chickenlomein.jpeg',
        description: 'Garlicky Chicken with Lo Mein noodles, Carrots & Onions with Green Beans.',
        calories: '281 cal/serv',
        rating: 4.0,
        numReviews: 10,
    },
    {   id: 3,
        title: 'Chimichurri Steak',
        img: '/images/chimisteak.jpeg',
        description: 'Homemade chimichurri sauce meets a classic grilled Flank Steak accompanied with charred corn choux and fingerling potatoes.',
        calories: '496 cal/serv',
        rating: 4.5,
        numReviews: 25,
    },
    {   id: 4,
        title: 'Deconstructed Mahi tacos',
        img: '/images/fishtacos.jpeg',
        description: 'Grilled Mahi-Mahi fish accompanied with pickled onions, cabbage & lettuce, corn salsa and spiced lime crema.',
        calories: '368 cal/serv',
        rating: 3.5,
        numReviews: 15,
    },
    {   id: 5,
        title: 'Honey Garlic Glazed Salmon',
        img: '/images/HoneyGlazedSalmon.jpeg',
        description: 'Sweet and garlicky honey glazed Salmon accompanied with mashed potatoes and chili green beans',
        calories: '399 cal/serv',
        rating: 4.5,
        numReviews: 30,
    },
    {   id: 6,
        title: 'SouthWest Turkey Bowl',
        img: '/images/turkeybowl.jpeg',
        description: 'Lean ground turkey flavored with homemade taco seasoning accompanied with SouthWestern veggies, black beans, lettuce and lime and cilantro rice',
        calories: '463 cal/serv',
        rating: 3.5,
        numReviews: 10,
    }
]